=== MariiaKushel/jvd-task3/src/main/resources/data/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.javacourse.by/medicins"
	xmlns:c="http://www.javacourse.by/medicins">

	<complexType name="medicins">
		<sequence>
			<element name="name" type="string"></element>
			<element name="pharm" type="string"></element>
			<element name="group" type="c:group-atc"></element>
			<element name="analogs" type="c:list-string"></element>
			<element name="version" type="c:version"></element>
		</sequence>
		<attribute name="id" type="c:medicins-id" use="required" />
		<attribute name="out-of-prodaction" type="boolean" use="optional" default="false" />
	</complexType>

	<complexType name="medicin">
		<complexContent>
			<extension base="c:medicins">
				<sequence>
					<element name="code-cas" type="c:code-cas" />
					<element name="active-substance" type="string" />
					<element name="need-recipe" type="boolean" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="baa">
		<complexContent>
			<extension base="c:medicins">
				<sequence>
					<element name="composition" type="c:list-string" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="version">
		<sequence>
			<element name="country" type="c:country" />
			<element name="certificate" type="string" />
			<element name="data-from" type="gYearMonth"></element>
			<element name="data-to" type="gYearMonth"></element>
			<element name="pack" type="c:pack"></element>
		</sequence>
	</complexType>

	<simpleType name="group-atc">
		<restriction base="string">
			<enumeration value="group-a" />
			<enumeration value="group-b" />
			<enumeration value="group-c" />
			<enumeration value="group-d" />
			<enumeration value="group-d" />
			<enumeration value="group-h" />
			<enumeration value="group-j" />
			<enumeration value="group-l" />
			<enumeration value="group-m" />
			<enumeration value="group-n" />
			<enumeration value="group-p" />
			<enumeration value="group-r" />
			<enumeration value="group-s" />
			<enumeration value="group-v" />
		</restriction>
	</simpleType>

	<simpleType name="country">
		<restriction base="string">
			<enumeration value="Germany" />
			<enumeration value="Belarus" />
			<enumeration value="Belgium" />
			<enumeration value="Russia" />
			<enumeration value="Czech Republic" />
			<enumeration value="India" />
			<enumeration value="Israel" />
			<enumeration value="Poland" />
			<enumeration value="China" />
		</restriction>
	</simpleType>

	<simpleType name="pack">
		<restriction base="string">
			<enumeration value="Pill" />
			<enumeration value="Capsule" />
			<enumeration value="Powder" />
			<enumeration value="Ointment" />
			<enumeration value="Gel" />
			<enumeration value="Solution For Injection" />
			<enumeration value="Mixture" />
			<enumeration value="Aerosol" />
			<enumeration value="Drop" />
		</restriction>
	</simpleType>

	<simpleType name="code-cas">
		<restriction base="string">
			<pattern value="\d{1,7}-\d{2}-\d" />
		</restriction>
	</simpleType>

	<simpleType name="medicins-id">
		<restriction base="ID">
			<pattern value="\w{1,10}" />
		</restriction>
	</simpleType>

	<simpleType name="list-string">
		<list itemType="string" />
	</simpleType>

	<element name="medicins" type="c:medicins" abstract="true"></element>
	<element name="medicin" type="c:medicin"
		substitutionGroup="c:medicins"></element>
	<element name="baa" type="c:baa"
		substitutionGroup="c:medicins"></element>

	<element name="catalog">
		<complexType>
			<sequence>
				<element ref="c:medicins" maxOccurs="unbounded"></element>
			</sequence>
		</complexType>
	</element>

</schema>

=== MariiaKushel/jvd-task3/src/test/resources/testData/medicinsTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<c:catalog
	xmlns:c="http://www.javacourse.by/medicins/test"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.javacourse.by/medicins src/test/resources/testData/schema.xsd ">

	<c:medicin id="m1" >
		<name>Ibuprofen</name>
		<pharm>Med Company</pharm>
		<group>group-m</group>
		<analogs>Paracetomol Noshpa</analogs>
		<version>
			<country>Israel</country>
			<certificate>1255.DF54565.1587RE</certificate>
			<data-from>2021-01</data-from>
			<data-to>2022-01</data-to>
			<pack>Pill</pack>
		</version>
		<code-cas>1235-67-8</code-cas>
		<active-substance>obezbolin</active-substance>
		<need-recipe>false</need-recipe>
	</c:medicin>

	<c:baa id="m2" out-of-prodaction="true">
		<name>Health helper</name>
		<pharm>Other Med Company</pharm>
		<group>group-a</group>
		<analogs>Gooder Weller</analogs>
		<version>
			<country>Russia</country>
			<certificate>1889.589-31.SS157</certificate>
			<data-from>2020-07</data-from>
			<data-to>2023-01</data-to>
			<pack>Gel</pack>
		</version>
		<composition>Mentol Oil</composition>
	</c:baa>

</c:catalog>
